---
- name: Install a webserver and set up a hello world page
  hosts: webservers
  become: yes
  remote_user: ubuntu
  become_user: root
  become_method: sudo

  roles:
    - docker
    - nginx-deploy

